name: Test

on:
  push:
    branches:
      - feat-update-projects-version

jobs:
  test-new-actions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/Checkout@v4

      - run: echo "Perchè test non parte?"

      - uses: ./.github/actions/upgrade-apps
