name: Test

on:
  push:
    branches:
      - feat-update-projects-version

jobs:
  test-new-actions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/Checkout@v4

      - id: upgrade-apps
        shell: bash
        run: |
          echo "upgrade-android=false" >> "$GITHUB_OUTPUT"
          echo "upgrade-ios=false" >> "$GITHUB_OUTPUT"

      - shell: bash
        id: check-node
        run: |
          if type node > /dev/null 2>&1 && which node > /dev/null 2>&1 ;then
            echo "install-node=false" >> "$GITHUB_OUTPUT"
          else
            echo "install-node=true" >> "$GITHUB_OUTPUT"
          fi

      - shell: bash
        if: steps.check-node.outputs.install-node
        run: |
          echo "install-node: ${{ steps.check-node.outputs.install-node }}"

      - id: get-version
        uses: ./.github/actions/get-version

      - shell: bash
        run: |
          echo "${{ toJson(steps.get-version) }}"
          echo "${{ toJson(steps.upgrade-apps) }}"

      - if: steps.upgrade-apps.outputs.upgrade-android == true
        name: Update gradle version
        uses: damienaicheh/update-android-version-gradle-action@v1.0.0
        with:
          build-gradle-path: './android/app/build.gradle'
          version-code: ${{ github.run_number }}
          version-name: ${{ steps.get-version.outputs.current-version }}
          print-file: true

      - if: steps.upgrade-apps.outputs.upgrade-ios == true
        uses: ./.github/actions/ios
        with:
          project-name: ${{ steps.get-version.outputs.name }}
          version: ${{ steps.get-version.outputs.version }}
